### PR TITLE
SnapshotGenerator - Implement Grahame's unit tests

### PR DESCRIPTION
**Pull request by wmrutten**
Fix for #1051 

Implement automated SnapshotGenerator unit tests from HAPIFHIR github repository:
https://github.com/hapifhir/org.hl7.fhir.core/tree/master/org.hl7.fhir.r5/src/test/resources/snapshot-generation

Also found & fixed some bugs in the .NET SnapshoGenerator

### CODE REVIEW

**Comment by wmrutten** [comment]
Note: this pull requests includes changes from issue #1074 (cherry picked from bugfix branch)

**Comment by wmrutten** [comment]
Woops, accidentally broke some unrelated unit tests... fixed

**Comment by wmrutten** [comment]
Yay!

**Comment by wmrutten** [comment]
Improved logic to correctly handle/merge mixed representations of type slices (explicit slicing vs. element renaming).

**Comment by wmrutten** [comment]
Yay!

**Comment by wmrutten** [comment]
R4: normalize renamed type slices in diff
Snapshot should always specify fully expanded slice definition; no element renaming.

e.g. diff: `valueString` => snap: `value[x]:valueString`

Also, `SnapshotGenerator` now automatically generates and assigns missing `sliceName` values for explicit type slices constrained to a single type. Note that this feature modifies the specified `Differential` component itself.

**Comment by wmrutten** [comment]
Yay!

**Comment by ewoutkramer** [comment]
Included in #1089

**Pull request closed without merging**
