### PR TITLE
Fix: 999 SimpleQuantity issue

### PR DESCRIPTION
**Pull request by gstoian**
Fix: SimpeQuantity was treated by ModelInspector as FhirType and because of that the Quantity type was replaced in the "dataTypeClass" by SimpleQuantity.

### CODE REVIEW

**Comment by marcovisserFurore** [comment]
This PR will solve issue #999

**Comment by marcovisserFurore** [comment]
@wmrutten: can you also have a check on this PR?

**Comment by wmrutten** [comment]
@gstoian are you planning to also port this fix to the develop-r4 branch?

**Comment by marcovisserFurore** [comment]
> @gstoian are you planning to also port this fix to the develop-r4 branch?

@gstoian: no worries, I will do that

**Comment by janetr1023** [comment]
We are on R4 1.4.0 and still have this issue (although i see this fix listed in that release) for doseQuantity instead of doseSimpleQuantity.
I also tried the 1.5.0-beta1 prerelease and it too has the same issue.

**Pull request merged**
